list: $/renick/shortener/models/shortener/columns.yaml
modelClass: Renick\Shortener\Models\Shortener
title: 'renick.shortener::lang.plugin.menu_item'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'renick/shortener/shortenercontroller/update/:id'
